# Este es un flujo de trabajo básico para  comenzar con Github Actions.

name: CI

# Controla cuándo se ejecutará el flujo de trabajo
on:
  # Activa el flujo de trabajo en eventos de solicitud push o pull, pero solo para la rama "principal/main"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Me permite ejecutar el flujo de trabajo manualmente desde la pestaña Actions
  workflow_dispatch:

# Una ejecución/runner de flujo de trabajo se compone de uno o más trabajos/jobs que se pueden ejecutar de forma secuencial o en paralelo.
jobs:
  # Este flujo de trabajo contiene un único trabajo llamado "compilación/build"
  build:
    # El tipo de runner en el que se ejecutará el trabajo.
    runs-on: ubuntu-latest

    # Los pasos/steps representan una secuencia de tareas que se ejecutarán como parte del trabajo.
    steps:
      # Reviso mi repositorio en $GITHUB_WORKSPACE, para que el trabajo/job pueda acceder a él
      - uses: actions/checkout@v4

      # Ejecuta un solo comando usando el shell de runner
      - name: Run a one-line script
        run: echo Hello, world!

      # Ejecuta un conjunto de comandos usando el shell de runner
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
